stages:
  preprocess:
    cmd: python scripts/run_preprocess.py --input-path data/data.csv --output-path data/data_clean.csv
    deps:
    - data/data.csv
    - src/flexsaize/data/preprocessor.py
    - scripts/run_preprocess.py
    outs:
    - data/data_clean.csv
  
  split:
    cmd: python scripts/run_split.py --input-path-clean data/data_clean.csv --output-path-train data/train.csv --output-path-val data/val.csv --output-path-test data/test.csv --group-column file --test-size 0.1 --val-size 0.1
    deps:
      - data/data_clean.csv 
      - scripts/run_split.py
    outs:
      - data/train.csv 
      - data/val.csv   
      - data/test.csv  
  # train:
  #   cmd: python scripts/run_train.py --raw-input data/data_clean_withmeta.csv
  #   deps:
  #   - data/data_clean_withmeta.csv
  #   - src/flexsaize/models/train.py
  #   - scripts/run_train.py
  #   outs:
  #   - models/rf_model.pkl
