stages:
  preprocess:
    cmd: python scripts/run_preprocess.py --input-path data/data.csv --output-path data/data_clean.csv
    deps:
    - data/data.csv
    - src/flexsaize/data/preprocessor.py
    - scripts/run_preprocess.py
    outs:
    - data/data_clean.csv
  
  split:
    cmd: python scripts/run_split.py --input-path-clean data/data_clean.csv --output-path-train data/train.csv --output-path-val data/val.csv --output-path-test data/test.csv --group-column file --test-size 0.1 --val-size 0.1
    deps:
      - data/data_clean.csv 
      - scripts/run_split.py
    outs:
      - data/train.csv 
      - data/val.csv   
      - data/test.csv  
      
  train:
    cmd: >
      python scripts/run_train.py
      --input-path-train data/train.csv
      --input-path-val data/val.csv
      --input-path-test data/test.csv
      --target-col x,y,width,height
      --model-type ${train.model_type}
    deps:
      - data/train.csv 
      - data/val.csv   
      - data/test.csv  
      - scripts/run_train.py
      - src/flexsaize/train/model_trainer.py
      - src/flexsaize/models/model_config.py
    params:
      - train.active_hyperparams
      - train.model_type
    metrics:
      - metrics.json:
          cache: false
