stages:
  train:
    cmd: python scripts/run_train.py --raw-input data/data.csv --out-clean 
      data/data_clean.csv
    deps:
    - data/data.csv
    - src/flexsaize/models/evaluate.py
    - src/flexsaize/data/preprocessor.py
    - src/flexsaize/data/splitter.py
    - src/flexsaize/models/train.py
    outs:
    - data/data_clean.csv
