train:
  model_type: XGBoost
  # Definimos una clave para almacenar todos los hyperparams del modelo activo
  active_hyperparams:
    RandomForest:
      n_estimators: 300
      max_depth: 15
      random_state: 42
    XGBoost:
      n_estimators: 400
      learning_rate: 0.05
      max_depth: 10
    SVR:
      C: 1.0
    StackingV2:
      rf__n_estimators: 200
      xgb__n_estimators: 300
      svr__C: 1.0
      svr__kernel: "rbf"
      final__n_estimators: 200
    HGB Regressor:
      learning_rate: 0.1
      max_depth: 10
      